#!/usr/bin/env bash
##
## ~/.bin/rose
##
## Authors:
##  Iyyel <github.com/iyyel>
##
## rose script
##

read -r -d '' rose <<- EOM
\\033c\\033[31m    .--.---.
   ( \\'--'/ )
  ( '..-...' )
   '.'-._.'.'
 \\033[34m   <'-.,.->
       \`\\(   _
       < \\ / \\
       __ \\\\|_/
      /  \\ \\\\
       '--'.\\ >
             \\\\\\033[0m
EOM

printf "%b\\n\\n" "$rose"
