#!/usr/bin/env bash
#
# ~/.scripts/lock
#
# Authors:
#   Iyyel <github.com/iyyel>
#

icon="$HOME/personal/media/pictures/wallpapers/04.jpg"
tmpbg='/tmp/screenlock.png'

(( $# )) && { icon=$1; }

scrot "$tmpbg"
mogrify "$tmpbg" -blur 0x6 "$tmpbg"
convert "$tmpbg" "$icon" -gravity center -composite -matte "$tmpbg"
i3lock -u -i "$tmpbg"
rm -f /tmp/screenlock.png
