#!/usr/bin/env bash

set -e

# Disable WoL and the link for my ethernet device
ethernet_dev='enp0s31f6'
ethtool -s "$ethernet_dev" wol d
ip link set "$ethernet_dev" down

# Powertop powersavings
echo '1500' > '/proc/sys/vm/dirty_writeback_centisecs'
echo '0' > '/proc/sys/kernel/nmi_watchdog'
# echo 'auto' > '/sys/bus/usb/devices/1-9/power/control'
echo 'auto' > '/sys/bus/i2c/devices/i2c-0/device/power/control'
echo 'auto' > '/sys/bus/i2c/devices/i2c-2/device/power/control'
# echo 'auto' > '/sys/bus/usb/devices/1-3/power/control'
echo 'auto' > '/sys/bus/i2c/devices/i2c-1/device/power/control'
echo 'auto' > '/sys/bus/i2c/devices/i2c-3/device/power/control'
echo 'auto' > '/sys/bus/pci/devices/0000:00:04.0/power/control'
echo 'auto' > '/sys/bus/pci/devices/0000:03:00.0/power/control'
echo 'auto' > '/sys/bus/pci/devices/0000:00:08.0/power/control'
echo 'auto' > '/sys/bus/pci/devices/0000:00:1f.0/power/control'
echo 'auto' > '/sys/bus/pci/devices/0000:00:14.3/power/control'
echo 'auto' > '/sys/bus/pci/devices/0000:00:1f.5/power/control'
echo 'auto' > '/sys/bus/pci/devices/0000:00:12.0/power/control'
echo 'auto' > '/sys/bus/pci/devices/0000:00:1d.4/power/control'
echo 'auto' > '/sys/bus/pci/devices/0000:00:14.2/power/control'
echo 'auto' > '/sys/bus/pci/devices/0000:00:16.3/power/control'
echo 'auto' > '/sys/bus/pci/devices/0000:00:1f.6/power/control'
echo 'auto' > '/sys/bus/pci/devices/0000:00:02.0/power/control'
echo 'auto' > '/sys/bus/pci/devices/0000:00:14.0/power/control'
echo 'auto' > '/sys/bus/pci/devices/0000:00:00.0/power/control'
echo 'auto' > '/sys/bus/pci/devices/0000:00:1f.3/power/control'
echo 'enabled' > '/sys/class/net/wlp0s20f3/device/power/wakeup'
# echo 'enabled' > '/sys/bus/usb/devices/1-9/power/wakeup'
# echo 'enabled' > '/sys/bus/usb/devices/usb1/power/wakeup'
# echo 'enabled' > '/sys/bus/usb/devices/1-10/power/wakeup'
# echo 'enabled' > '/sys/bus/usb/devices/usb2/power/wakeup'

exec chpst -b powersave pause
