#!/usr/bin/env zsh

# Set display resolution (GENERATE NEW!)
xrandr --output VIRTUAL1 --off --output eDP1 --primary --mode 2560x1440 --pos 0x0 --rotate normal --output DP1 --off --output HDMI2 --off --output HDMI1 --off --output DP2 --off &

# Wallpaper
hsetroot -fill ~/personal/wallpapers/01.png &

# Start compton
compton --config ~/.config/compton/config &

# MPD daemon start (if no other user instance exists)
[ ! -s ~/.config/mpd/mpd.pid ] && mpd &>/dev/null &

# Start dunst
dunst &

# load polybar
~/bin/launch &

# bspwm configuration
bspc config border_width                1
bspc config window_gap                  30
bspc config top_padding                 5
bspc config left_padding                8
bspc config right_padding               8
bspc config bottom_padding              15

bspc config split_ratio          	    0.50
bspc config borderless_monocle   	    true
bspc config gapless_monocle      	    true
bspc config focus_by_distance    	    true
bspc config history_aware_focus  	    true
bspc config center_pseudo_tiled         true
bspc config auto_cancel                 true
bspc config click_to_focus 			    false
bspc config adaptive raise 			    true

bspc config normal_border_color         "#131313"
bspc config focused_border_color        "#783E57"
bspc config presel_feedback_color       "#783E57"

bspc monitor -d    

bspc rule -a Steam desktop=^3 follow=on split_dir=right
bspc rule -a URxvt:updates state=floating
bspc rule -a URxvt:pulsemixer state=floating
bspc rule -a URxvt:mutt desktop=^2 follow=on
bspc rule -a URxvt:weechat desktop=^2 follow=on
bspc rule -a Gimp desktop=^4 follow=on
bspc rule -a URxvt:vpn desktop=^5 follow=on state=floating
bspc rule -a URxvt:upass state=floating

# Start xautolock (This requires xautolock and i3lock packages)
xautolock -time 15 -locker '~/bin/lock'
