#!/usr/bin/env sh
#
# ~/.config/bspwm/bspwmrc
#
# Authors:
#  Iyyel <github.com/iyyel>
#
# bspwm configuration file.
#

# Colors
bg=$(get_xres color0)
fg=$(get_xres color7)
acc=$(get_xres color8)

# bspwm configuration
bspc monitor -d 1 2 3 4 5

bspc config border_width           1
bspc config window_gap             30
bspc config top_padding            0
bspc config left_padding           0
bspc config right_padding          0
bspc config bottom_padding         0

bspc config split_ratio            0.50
bspc config center_pseudo_tiled    true
bspc config borderless_monocle     true
bspc config gapless_monocle        true

# bspwm colors
bspc config normal_border_color    "$bg"
bspc config active_border_color    "$bg"
bspc config focused_border_color   "$acc"
bspc config presel_feedback_color  "$acc"

# Window rules
#bspc rule -a qutebrowser desktop=^5 follow=on
#bspc rule -a Steam desktop=^4 state=floating follow=on
#bspc rule -a Keepassx2 desktop=^3 state=floating follow=on
#bspc rule -a URxvt:ncmpcpp desktop=^1 follow=on
#bspc rule -a URxvt:htop desktop=^1 follow=on
#bspc rule -a URxvt:weechat desktop=^1 follow=on
#bspc rule -a URxvt:vpn desktop=^1 follow=on

#bspc rule -a URxvt:updates state=floating
#bspc rule -a URxvt:listupg state=floating
