#!/usr/bin/env zsh
#
# ~/.config/bspwm/bspwmrc
#
# Authors:
#   Iyyel <github.com/iyyel>
#

# bspwm initial options
bspc config border_width            1
bspc config window_gap              30
bspc config top_padding             20
bspc config left_padding            20
bspc config right_padding           20
bspc config bottom_padding          20

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_by_distance       true
bspc config history_aware_focus     true
bspc config center_pseudo_tiled     true
bspc config auto_cancel             true

bspc config normal_border_color     "#131313"
bspc config focused_border_color    "#51C4D4"
bspc config presel_feedback_color   "#51C4D4"
bspc config urgent_border_color     "#51C4D4"

bspc monitor -d 1 2 3 4 5 6 7 8

# Application rules
bspc rule -a qutebrowser desktop='^8' follow=on
bspc rule -a Steam desktop='^7'
bspc rule -a Keepassx2 desktop='^6' follow=on

bspc rule -a URxvt:ncmpcpp desktop='^1' follow=on
bspc rule -a URxvt:htop desktop='^1' follow=on
bspc rule -a URxvt:weechat desktop='^1' follow=on
bspc rule -a URxvt:vpn desktop='^1' follow=on
bspc rule -a URxvt:mutt desktop='^2' follow=on

# Set display resolution
xrandr --output VIRTUAL1 --off --output eDP1 --primary --mode 2560x1440 --pos 0x0 --rotate normal --output DP1 --off --output HDMI2 --off --output HDMI1 --off --output DP2 --off &
 
# Wallpaper
hsetroot -center ~/personal/wallpapers/01.png

# Start compton
compton --config ${HOME}/.config/compton/config &

# MPD daemon start (if no other user instance exists)
[ ! -s ~/.config/mpd/mpd.pid ] && mpd &>/dev/null

# Start dunst
# dunst &

# Start yabar
yabar -c ${HOME}/.config/yabar/yabar.conf &

# Start xautolock (This requires xautolock and i3lock packages)
xautolock -time 15 -locker '${HOME}/.scripts/lock'
