#!/usr/bin/env bash

ramp10=󰁺
ramp20=󰁻
ramp30=󰁼
ramp40=󰁽
ramp50=󰁾
ramp60=󰁿
ramp70=󰂀
ramp80=󰂁
ramp90=󰂂
ramp100=󰁹

bat0path="/sys/class/power_supply/BAT0"
bat1path="/sys/class/power_supply/BAT1"

bat0=`cat $bat0path/capacity`
status0=`cat $bat0path/status`

print_battery()
{
    cap=$1
    status=$2

    if [[ $status == "Discharging" ]]; then
        echo "lol"
        ifg=^c#83A598^
    elif [[ $status == "Full" ]]; then
        ifg=^c#83A598^
    else
        ifg=^c#B8BB26^
    fi

    if [[ $cap -lt 10 ]]; then
        echo "$ifg$ramp10 ^d^$cap%"
    elif [[ $cap -lt 20 ]]; then
        echo "$ifg$ramp20 ^d^$cap%"
    elif [[ $cap -lt "30" ]]; then
        echo "$ifg$ramp30 ^d^$cap%"
    elif [[ $cap -lt "40" ]]; then
        echo "$ifg$ramp40 ^d^$cap%"
    elif [[ $cap -lt "50" ]]; then
        echo "$ifg$ramp50 ^d^$cap%"
    elif [[ $cap -lt "60" ]]; then
        echo "$ifg$ramp60 ^d^$cap%"
    elif [[ $cap -lt "70" ]]; then
        echo "$ifg$ramp70 ^d^$cap%"
    elif [[ $cap -lt "80" ]]; then
        echo "$ifg$ramp80 ^d^$cap%"
    elif [[ $cap -lt "90" ]]; then
        echo "$ifg$ramp90 ^d^$cap%"
    elif [[ $cap -le "100" ]]; then
        echo "$ifg$ramp100 ^d^$cap%"
    fi
}

# check if bat1 path exists
if [[ -d "$bat1path" ]]; then
    # if bat1 exists, get its capacity and status
    bat1=`cat /sys/class/power_supply/BAT1/capacity`
    status1=`cat /sys/class/power_supply/BAT1/status`
    
    # find out which one has a larger capacity 
    if [[ $bat0 -gt $bat1 ]]; then
        # bat0 is the correct battery
        print_battery $bat0 $status0
    else
        # bat1 is the correct battery
        print_battery $bat1 $status1
    fi
else
    # bat0 is correct
    print_battery $bat0 $status0
fi
