#!/usr/bin/env bash

low=󱃃
med=󰔏
high=󱃂

lfg=^c#FB4934^
mfg=^c#FB4934^
hfg=^c#FB4934^
tfg=^d^

temp=`sensors | awk '/^Core 1:/{ print $3 }' | sed "s/.*+//;s/\..*//"`
cels=°C

if (( $temp < 50 )); then
    echo "$lfg$low $tfg$temp$cels"
elif (( $temp < 70)); then
    echo "$mfg$med $tfg$temp$cels"
else 
    echo "$hfg$high $tfg$temp$cels"
fi
