#!/usr/bin/env bash
interface=`ls /sys/class/net | grep "\bw.*"`
[[ -z "$interface" ]] && exit

rampdown=󰤮
ramp0=󰤯
ramp1=󰤟
ramp2=󰤢
ramp3=󰤥
ramp4=󰤨

dfg=^c#cc241d^
ufg=^c#b16286^
tfg=^d^

con=`cat /sys/class/net/w*/operstate`
if [[ $con == "down" ]]; then
    echo "$dfg$rampdown $tfg0%"
else
    ssid=`nmcli device show | grep "$INTERFACE" -m 1 -A 5 | grep GENERAL.CONNECTION: -m 1 | awk '{print $2}'`
    signal=`grep "^\s*w" /proc/net/wireless | awk '{ print int($3 * 100 / 70) }'`
    if [[ $signal < "20" ]]; then
        echo "$ufg$ramp0 $tfg$ssid"
    elif [[ $signal < "40" ]]; then
        echo "$ufg$ramp1 $tfg$ssid"
    elif [[ $signal < "60" ]]; then
        echo "$ufg$ramp2 $tfg$ssid"
    elif [[ $signal < "80" ]]; then
        echo "$ufg$ramp3 $tfg$ssid"
    else
        echo "$ufg$ramp4 $tfg$ssid"
    fi
fi
