#!/usr/bin/env zsh
#
# ~/.config/yabar/openvpn
#
# Authors: 
#   Iyyel <github.com/iyyel>
#

vpn() {
    con=`ip link | grep 'tun'`

    if [[ -n $con ]]; then
        echo 'VPN: connected'
    else 
        echo 'VPN: disconnected'
    fi
}

vpn
